### ISSUE TITLE
Cannot Test Import/Export with Demo Version

### ISSUE THREAD

**Issue by jasonmckinney66** [AcclaroInc/craft-translations#10]
Running the demo, seems like it is impossible to save an Order and therefor impossible to test the Import/Export functionality. Am I missing something? Thanks in advance.

**Comment by sidedwards** [comment]
@jasonmckinney66 Hi Jason, in trial mode you can "submit" single entry orders but the "save" functionality is disabled as it's primarily used for adding multiple entries to an order (bulk translating).

Does that answer your question?

**Comment by jasonmckinney66** [comment]
Hi. Thanks for the quick response. Sounds like it's not possible to test the Import/Export functionality. Is it possible to get to this screen in Trial Mode?
<img width="589" alt="Screenshot 2019-05-14 14 33 29" src="https://user-images.githubusercontent.com/5642154/57733937-8e1be000-7655-11e9-8156-0989438fb46c.png">

**Comment by sidedwards** [comment]
@jasonmckinney66 It is possible to test Import/Export in trial mode. Have you created a local translator prior to creating the order?

**Comment by jasonmckinney66** [comment]
Yes. I have created a translator and created an order by selecting an entry.
<img width="512" alt="Screenshot 2019-05-14 14 38 03" src="https://user-images.githubusercontent.com/5642154/57734095-f9fe4880-7655-11e9-9d23-8d1883445217.png">

**Comment by sidedwards** [comment]
@jasonmckinney66 Okay, and on the order submission page, do you see a "Submit" button at the bottom?

**Comment by jasonmckinney66** [comment]
Yes. I have it.

<img width="961" alt="Screenshot 2019-05-14 14 41 29" src="https://user-images.githubusercontent.com/5642154/57734257-5fead000-7656-11e9-92ec-d569372a3d71.png">

**Comment by sidedwards** [comment]
@jasonmckinney66 Okay, once you submit the order you should be able to see it in the "Orders" tab where you can click into for more details and Export/Import.

Are you receiving any errors during submission?

**Comment by jasonmckinney66** [comment]
No errors. The screen refreshes and the order process seems to start over. If I navigate directly to the orders tab, there is no order.

<img width="993" alt="Screenshot 2019-05-14 14 45 30" src="https://user-images.githubusercontent.com/5642154/57734648-2e263900-7657-11e9-8500-3e35ef786d05.png">
<img width="536" alt="Screenshot 2019-05-14 14 47 09" src="https://user-images.githubusercontent.com/5642154/57734656-33838380-7657-11e9-9c7a-a0e44694e7eb.png">

**Comment by sidedwards** [comment]
@jasonmckinney66 I'm sorry to hear that you're having trouble creating an order, would you be available for a screen-share tomorrow to review the site configuration? Alternatively, you can send a copy of the database to support@acclaro.com along with a link to this issue so that we can reproduce on our end.

In the meantime, maybe double check your Section site settings to ensure it's enabled for the target language? You can also browse our [Wiki](https://github.com/AcclaroInc/craft-translations/wiki) to make sure the rest of the settings are correct.

**Comment by jasonmckinney66** [comment]
Yes. I can be available during working hours in PST. I will email you at support so you have my direct email. Thanks for the excellent service.

**Comment by sidedwards** [comment]
This issue was related to "Propagate entries across all enabled sites" setting being disabled in _Sections_ which caused order submission failure.

Wiki reference: [Getting Started: Sections](https://github.com/AcclaroInc/craft-translations/wiki/Getting-Started#sections)
