### ISSUE TITLE
Store static translations in the DB, volume, or some other location than directly on the server.

### ISSUE THREAD

**Issue by taylordaughtry** [AcclaroInc/craft-translations#100]
If I'm understanding the code correctly, the plugin is currently storing static translations that are added/modified by the user in the translations file itself. If the site's deployed via `git`, that file is overwritten and those changes are lost. (If the site uses any sort of multiple instance setup, this also causes issues.)

Here's where the changes would (possibly) need to be made:
https://github.com/AcclaroInc/craft-translations/blob/075a2b70d9ecd5a637c9da0c374e071e24c576e2/src/services/repository/StaticTranslationsRepository.php#L184-L208

**Comment by sidedwards** [comment]
@taylordaughtry thanks for the suggestion, we'll look into this for an upcoming release.

**Comment by taylordaughtry** [comment]
@sidedwards Hey! Is there any chance we could get a faster patch for this one? It's currently a blocker for the client I'm working with at the moment. (We can't deploy without overwriting the static translations on production.)

**Comment by sidedwards** [comment]
@taylordaughtry we built our static translation architecture around Craft's [Static Message Translations](https://craftcms.com/docs/3.x/sites.html#static-message-translations) functionality which uses files (`lang/site.php`). So it seems less of a plugin issue and more of a Craft compatibility issue if I understand it correctly.

That said, it looks like others on the Discord channel have had the [same issue with Static Translations and git](https://discordapp.com/channels/456442477667418113/456442867163070466/733605942565929050). Could you try updating your `CRAFT_TRANSLATIONS_PATH` to a "higher" directory so it doesn't get overwritten?

**Comment by ifrimere** [comment]
@taylordaughtry - closing this issue for now as it appears to be a Craft core issue, but if you feel otherwise, please let us know and we can re-open. Thanks.
