### ISSUE TITLE
Export Translations Order entries to CSV file

### ISSUE THREAD

**Issue by huelabs** [AcclaroInc/craft-translations#102]
We ran into an issue after importing around 800 translated XML files in which the Draft preview links quit working. Our working Excel files that we were tracking the export/import process now had broken Draft preview links for the linguists. This is not ideal for the linguists during QA because they now have to log into Craft and preview each entry in the Craft UI.

Ideally, we could have mitigated the issue if the Translations plugin allowed exporting all Translations Order entries to CSV.

Overview: https://download.hamiltonsupport.com/wl/?id=ckCmwbMKvHEAFSzlStvqVhkSaGCrSAWC

**Comment by ifrimere** [comment]
@huelabs - thanks for the feature request. We have added to our roadmap and will let you know once it's available. As a workaround, perhaps the URLs in the xml files can be extracted programmatically to generate a spreadsheet of the URLs.  If the xml files were all upload to a CAT tool like MemoQ, the CAT tool might be able to do this too.

**Comment by huelabs** [comment]
Thanks @ifrimere, will do.
