### ISSUE TITLE
Small Text Change Suggestion

### ISSUE THREAD

**Issue by ainigo-metcalfe** [AcclaroInc/craft-translations#103]
Going through connectors for test case creation and noticed that we have SITE listed here instead of either Language or Locale.
Not an emergency just a suggestion - @ifrimere what do you think?

Contentful we use Locale
My Acclaro and plunet we say Source and Target LANGUAGE
so maybe we switch the craft one to one of those versus SITE?

![image](https://user-images.githubusercontent.com/53836618/95792569-c17ef600-0cb1-11eb-95f3-16273648116d.png)

**Comment by ifrimere** [comment]
@ainigo-metcalfe - this is because of Crafts nomenclature
