### ISSUE TITLE
Not super obvious if you need to pay for translations?

### ISSUE THREAD

**Issue by verbeeksteven** [AcclaroInc/craft-translations#11]
Hello,

I am not sure it is obvious but do I have to pay for translations using acclaro? Or does the $999 include translations? Is there limits? Would be nice to have a few more of those type of details on the readme/wiki/plugin details.

Thanks,

**Comment by michaelkriz** [comment]
@verbeeksteven Hi Steven, The $999 is for the plugin license and doesn't include Acclaro's translation service. Once you purchase the plugin you can get an optional API token for Acclaro's translation platform along with a pay-as-you-go service plan for professional translation services. Or you can export the content for translations elsewhere. We'll make sure to add this clarification and details to the plugin info. Thanks for the question and comment.
Michael
