### ISSUE TITLE
Blocks do not appear in translation export if they are not managed on per-site basis

### ISSUE THREAD

**Issue by Mosnar** [AcclaroInc/craft-translations#13]
I was trialing the plugin for a client who is currently getting a quote for a website translation job from Acclaro; however, I ran into a snag where fields with blocks (such as Supertable or Matrix) that have their blocks set to NOT be managed on a per-site basis, but have translatable content, do not appear as translatable content to this plugin.

For example, consider you have a content builder for building out detail pages with a matrix block. Say, you have a heading block, "Contact Us" and then a block for a form. The text within the blocks should be translatable; however, the format and structure of the blocks should not be translatable. This is currently possible with Craft; however, the Translations plugin is not aware of these blocks upon creating an order.

**Comment by sidedwards** [comment]
Hi, @Mosnar thanks for submitting this issue. In most cases when nested SuperTable or Matrix content is marked translatable, we just enable the parent block as well so the entire block structure is exported. That said, I'd be curious to see the use case in person. If there are legitimate reasons to keep the parent block disabled with nested fields enabled we'd be happy to add support.

**Comment by ifrimere** [comment]
Hi Ransom (@Mosnar) - in addition to the use case explanation, it would be great to have an understanding of how much source content is impacted by this situation, and if there's a workaround on the dev side, or if editing the capability of the translation plugin is a must-have for this end client's translation workflows. Thanks, Ira

**Comment by sidedwards** [comment]
@Mosnar Our next release addresses this and will be able to pull "translatable" content out of nested fields (Matrix, SuperTable, Neo) even if the block itself is managed globally.

**Comment by sidedwards** [comment]
Hi @Mosnar this was resolved in v1.2.0. I recommend updating to the latest version and confirming if that resolves the issue.
