### ISSUE TITLE
Button to create translation order on element index not appearing

### ISSUE THREAD

**Issue by Mosnar** [AcclaroInc/craft-translations#14]
I'm trialing this plugin for a client who is getting a quote for a site translation from Acclaro; however, there doesn't appear to be a button showing up to add multiple entries to an order on the element index screen. I am only able to create an order for a single entry once I've clicked into it. Having used the Craft 2 version, I don't believe this is expected behavior. 

![image](https://user-images.githubusercontent.com/3810939/60276253-42ea2380-98c9-11e9-8968-5fb4d7511ed1.png)

**Comment by sidedwards** [comment]
Hi, @Mosnar bulk translations are not available during the trial period. Once a license key is added bulk ordering is automatically enabled.

https://github.com/AcclaroInc/craft-translations#important-notes

**Comment by Mosnar** [comment]
Understood - makes perfect sense! As a note of feedback, I think it would be beneficial to be able to bulk-translate entries as long as they are sent directly to Acclaro for a quote. I'm currently working with Elizabeth at Acclaro to get an accurate word-count for a large translation estimate for our client, and this limitation makes that impossible to do accurately.

**Comment by sidedwards** [comment]
Duly noted. We can look into implementing this down the road. In the meantime, you can contact me at sid@reboundcreative and we can discuss in detail.

Thanks!
