### ISSUE TITLE
Support for section propagation method "custom"

### ISSUE THREAD

**Issue by BAM-Dennis** [AcclaroInc/craft-translations#167]
P&T added a new feature in craft 3.5.0 called PROPAGATION_METHOD_CUSTOM for sections.

see: https://github.com/craftcms/cms/blob/main/src/models/Section.php#L45

We are currently testing your plugin and this is a core requirement. Imagine the following scenario:
- Entry in "Site A" (Propagation Method custom)
- Export Content
- Import contentt
- Apply Translation --> Error because Draft for entry with id was not found

What craft does is, it lets you choose, if you want to have this specific Entry enabled in the target site. 
When in my order, the imported content is in status "Ready to apply", i need to have the option to "enable target site for entry" first and after that do the import, but it may not fail uncaught when pushing the apply button.

Are there any plans to support this feature, or at least resolve the bug?
Another option would also be, to just no allow to import into this entry as long as it not enabled for the target site.

**Comment by ifrimere** [comment]
@BAM-Dennis - thanks for reporting this. We will look into it and follow up with questions and ideas shortly.

**Comment by sidedwards** [comment]
@BAM-Dennis I did some initial testing with the  "Let each entry choose which sites it should be saved to" propagation method and as long as the Site was added to the Entry, even if disabled, applying translation drafts worked as expected.
<img width="371" alt="image" src="https://user-images.githubusercontent.com/11489608/118335297-9325fb00-b4cc-11eb-8c4a-3e1c401bf651.png">

Please try adding the sites to the Entry first before applying the drafts. If the issue still persists, please download and send a copy of the server logs to sedwards@acclaro.com? You can do this from within Craft through Translations > Settings > Send Logs.

Hopefully, this helps.

**Comment by BAM-Dennis** [comment]
@sidedwards thanks for youre reply.

i am totally aware, of how that works and what i need to do implement it. But we are in a scenario, where we have a few hundred entries in 34 different sites.

It is not the best user experience, for the editors, to import an order for multiple entries, and after applying trying to find out, which one of those multiple ones should be enabled.

what i suggest is an indicator in the order table, that in the first case should reflect, that an action is needed ("Site not yet enabled for this entry") or in addition give the importer the option to enable this site on the fly.

**Comment by sidedwards** [comment]
@BAM-Dennis rather than a manual action, what are your thoughts on adding logic for applying drafts to add target sites to the selected entries automatically? I think it's safe to assume we'd want the target site added and enabled for the Entry within the context of the translation order.

**Comment by BAM-Dennis** [comment]
@sidedwards I think it is safe to assume, at this point, that the entry for this site should be enabled and that the draft should be created.

The user has already brought a tranaslation file for this entry, so i think we are safe here!

**Comment by sidedwards** [comment]
@BAM-Dennis support for this was added in [Release/v1.10.5](https://github.com/AcclaroInc/craft-translations/releases/tag/v1.10.5)
