### ISSUE TITLE
FR: Allow for assets to be added to translation order even if not related to entry

### ISSUE THREAD

**Issue by chadcrowell** [AcclaroInc/craft-translations#168]
We have many assets on a 6 language site that are not attached to an entry, but do show up on the site. In our case, they are product documentation PDFs that are categorized and show up in search results for docs as well as categorized lists.

I don't believe adding an asset to an order upon upload makes sense, because it is unlikely that the asset title or any custom fields would have been populated at that time (title would just be made from the filename by Craft on upload). However, I do think a good idea would be to, on asset save, evaluate if the asset title in non-primary site languages is equivalent to the primary site title (so EN title == DE title, for instance) and if so, add that asset automatically to the open order. This does leave room for error however, and has to make a lot of assumptions, so it may not be ideal.

What I did in the old EE2 version of this with my custom translation module was, there was a custom field called "Needs Translation?" that was present on all entry types that could be translated. It's default value was true, so any time a new entry was added to the system, it would be "marked for translation". We had all PDFs setup as a file related to an entry so we could support translated titles and summaries for PDFs, so those got marked upon creation. With Craft, since assets can have custom fields just like entries, a good approach may be to have something akin to that Needs Translation field where entry sections, asset volumes, and even global sections can be selected to use it, and then, whenever an new entry in certain sections, asset in certain volumes, or variable in certain globals is added to the system, it is auto marked for translation, and then provide the ability to create a new order that includes all entries/assets/globals that are marked for translation. If this field was available even across existing entries/assets/globals, and when edited and saved, the plugin could auto mark an edited element for translation, those could be included as well in that new order.

**Comment by sidedwards** [comment]
Hi @chadcrowell, thank you for suggesting this feature.

As of [`release/2.0`](https://github.com/AcclaroInc/craft-translations/releases/tag/v2.0.0), you can translate Asset fields by adding the Asset to an Order directly v.s referencing within an Entry.
