### ISSUE TITLE
Allow translation of Asset titles

### ISSUE THREAD

**Issue by robmcfadden** [AcclaroInc/craft-translations#170]
Asset fields were recently added to the export: https://github.com/AcclaroInc/craft-translations/issues/8

This is great, but sometimes sites are using the title for the alt text instead of a field or for other reasons. If the title wasn't intentionally ignored for some reason, can we add that in?

https://github.com/robmcfadden/craft-translations/blob/asset-title-support/src/services/fieldtranslator/AssetsFieldTranslator.php#L40

Happy to make a PR for this. If this looks good, let me know which branch I should make the PR to. Thanks!

**Comment by ifrimere** [comment]
@robmcfadden - thanks for the ticket and more thanks for the PR offer. 

@sidedwards is going to look into this and will get back to you with any questions, requested edits to the PR proposal and guidance about the branch where it can be placed against.  

Thanks.

**Comment by sidedwards** [comment]
@robmcfadden great catch! We have existing logic to handle updating Asset titles from XML files, but must have missed it for file generation. Your proposed fix looks good and I've confirmed that it works as expected. Please create a new branch off of `master` called `bug/asset-title-fix`, and I can merge it in with our next release `v1.10.5`.

Thanks!

**Comment by robmcfadden** [comment]
@sidedwards Great, thanks! PR is going into `master` for now. Base branch can be changed to `release/1.10.5` once available.

**Comment by sidedwards** [comment]
@robmcfadden merged #172 into [`release/1.10.5`](https://github.com/AcclaroInc/craft-translations/compare/release/1.10.5), thanks for the contribution!
