### ISSUE TITLE
Notes Field Type

### ISSUE THREAD

**Issue by masonry47** [AcclaroInc/craft-translations#171]
We are wanting the translations plugin to support for this custom field type.

https://plugins.craftcms.com/notes

Thanks!

**Comment by sidedwards** [comment]
While investigating adding support for this plugin, we noticed that the original issue raised exists within standard draft workflows and isn't related to the Translations plugin.

Please see the attached screen recording for details; here are the steps to reproduce:

1. Create a new draft for an Entry containing a "Notes" field.
2. Refresh the page OR switch to a different site via the dropdown.
3. See issue; existing Notes disappear from the Draft.
4. Add a new Note to the Draft and publish it.
5. See issue; Notes added to the Draft aren't added to the Entry.

I recommend opening an issue with [ethercreative/notes](https://github.com/ethercreative/notes/issues/new) to see if this is something that they can address. Once resolved, everything should work as expected with Translation drafts.

## 📚 Resources:

https://user-images.githubusercontent.com/11489608/121733028-31978300-cab0-11eb-9fc7-ba9bed1cbbf2.mp4

**Comment by masonry47** [comment]
Got it, will do. Thanks!
