### ISSUE TITLE
Blank install of v1.10.5, creating order not working

### ISSUE THREAD

**Issue by BAM-Dennis** [AcclaroInc/craft-translations#179]
Hey,

we are currently testing around with your plugin. Creating a blank craft instance and installing the latest version fails with an error when submitting an order.

if we install 1.10.4 first und upgrade to 1.10.5 after that it works. So i think there is something missing in some migrations.

**Comment by sidedwards** [comment]
Hi @BAM-Dennis, thanks for reaching out; v1.10.5 included a new database column that was missing from install.php. Please try updating to [v1.10.6](https://github.com/AcclaroInc/craft-translations/releases/tag/v1.10.6) to resolve the issue. Thanks!
