### ISSUE TITLE
Indexing Error on Import

### ISSUE THREAD

**Issue by matthewmrotter** [AcclaroInc/craft-translations#183]
We're applying an import/export of a page with a matrix block. 

The matrix block goes text 1->image->text 2->text  3 but when the translation is applied, text 3 is in text 2's spot and nothing appears in text 3. 

Craft CMS 3.5.18
Translations v1.9.4

**Comment by sidedwards** [comment]
Hi @matthewmrotter, can you please try updating the plugin to a more recent release and see if that resolves the issue?

**Comment by matthewmrotter** [comment]
@sidedwards does the new version of Translations require an updated version of Craft as a dependency? Don't see the option to upgrade in the CP

**Comment by sidedwards** [comment]
@matthewmrotter v1.10.0+ requires Craft ^3.6.0; is it possible to update Craft?

**Comment by sidedwards** [comment]
@matthewmrotter, just following up, did upgrading resolve your issue?

**Comment by matthewmrotter** [comment]
We've been unable to do a content freeze to update the site yet, I'll make this as closed and we'll test it out whenever we're able to update. 

Thanks!
