### ISSUE TITLE
When importing translated content, an error of `Call to undefined method DOMNodeList::getAttribute()` is occasionally thrown.

### ISSUE THREAD

**Issue by taylordaughtry** [AcclaroInc/craft-translations#188]
Based on a quick review locally, it appears the error's coming specifically from `ImportFiles.php:104`—where the `source-site` is being fetched.

I just emailed a copy of the project config and the zip file with the XML the client's attempting to import!

**Environment:**
- Craft Pro `3.6.17`
- Acclaro `v1.10.6`
- PHP version `7.3.29`

**Comment by sidedwards** [comment]
Thanks, @taylordaughtry, let me take a look and get back to you with more info.

**Comment by taylordaughtry** [comment]
Hi @sidedwards! Following up on our Slack conversation: last we saw this, the issue ended up coming from something that's happening internally when the Acclaro team updates translation file(s), moreso than a plugin issue.

I know was a while back, but were you ever able to suss out where that's happening, by chance?

**Comment by ifrimere** [comment]
@taylordaughtry - if your investigations yield results that something is up with the translation files status/formatting, etc..., and not the plugin, please work directly with the project manager for the customer, who in turn can work with the localization engineering team to make changes for the translation files format. Thanks.

**Comment by taylordaughtry** [comment]
@sidedwards Hi! Update on this issue—the client encountered it again! I've separately emailed a copy of the ZIP file that's causing the issue.

I thought of a few areas where it could _possibly_ be coming from:

- The file upload process itself within the plugin (perhaps the encoding of these specific files isn't able to be coerced into UTF-8)
- In `ImportFiles.php:74` the plugin declares UTF-8, but then later calls `loadXML()`, which seems to ignore the encoding set in the Document itself. (Found the thought [here](https://www.php.net/manual/en/domdocument.loadxml.php#124390) + tested a bit locally)

**Comment by sidedwards** [comment]
Hi @taylordaughtry, thanks for following up. While testing locally, did you try explicitly setting the encoding after `loadXML()` with the `$xmlDoc->encoding = "utf-8";` example in the reference above?

If you're able to create an order on a staging environment that consistently reproduces this issue, that would be a huge help in getting to the bottom of this.

**Comment by taylordaughtry** [comment]
I did, with no change in the result, unfortunately. I'll look into pulling the prod DB down to staging for you while you're looking at the issue on your side!

**Comment by sidedwards** [comment]
@taylordaughtry thank you, that would be great!

**Comment by sidedwards** [comment]
This issue occurred when there were specific XML validation errors (i.e., "double hyphen within comment") within `.zip` files.

When uploading a ZIP with a file containing the invalid XML:

```xml
<!-- INVALID XML <content resname="--"></content> -->
```

it triggers the display error notice:

```
Call to undefined method DOMNodeList::getAttribute()
```

and posts the following message in the Order activity log:
```
Getting unknown property: craft\elements\Asset::getFilename
```

[`release/2.0`](https://github.com/AcclaroInc/craft-translations/releases/tag/v2.0.0) provides more useful activity log errors to help catch tricky invalid XML errors.
![image](https://user-images.githubusercontent.com/11489608/135347360-00452669-4c3f-49ad-8674-5b7d4cc38f2b.png)
