### ISSUE TITLE
Import xml/zip file to translation order failing

### ISSUE THREAD

**Issue by vikdialpad** [AcclaroInc/craft-translations#19]
There seems to be a bug when we tried to import xml/zip file to translation order.
Following is SQL error message we’re getting when `Go!` button is clicked after xml/zip file is uploaded to field above:
`SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "id" violates not-null constraint
DETAIL: Failing row contains (null, 1, 5, Talk Page, トークページ, 2019-08-13 21:39:54, 2019-08-13 21:39:54, b46dde54-1bb3-405e-999f-c4b31e7a3214).
The SQL being executed was: INSERT INTO "dp_translations_translations" ("id", "sourceSite", "targetSite", "source", "target", "dateCreated", "uid", "dateUpdated") VALUES (NULL, 1, 5, 'Talk Page', 'トークページ', '2019-08-13 21:39:54', 'b46dde54-1bb3-405e-999f-c4b31e7a3214', '2019-08-13 21:39:54') RETURNING "id"`

We’re using:
Craft: 3.1.33
PHP: 7.1
PGSQL version: 11.4 (same error happens on 9.6 and 10.x)

Any thoughts on the cause ?

**Comment by sidedwards** [comment]
@vikdialpad Could you please share which version of the plugin you're using?

**Comment by vikdialpad** [comment]
@sidedwards plugin version is 1.1.1

**Comment by sidedwards** [comment]
Hi @vikdialpad I tested with the following requirements and didn't run into any issues on import
- Craft: 3.1.33
- PHP: 7.1
- PGSQL: 9.6

It's possible that it is a file or settings configuration issue. Please email me at sid@reboundcreative.com so I can get some additional details.

**Comment by ifrimere** [comment]
This issue is in progress of being fixed. It will be included in a v1.1.x patch (for Craft 3.1 sites) and also placed into the 1.2.x master code branch (for Craft 3.2+ sites)

**Comment by vikdialpad** [comment]
That's great to hear. Thank you. Any idea on the timeline ?

**Comment by ifrimere** [comment]
Hi @vikdialpad - we are feeling pretty good about having this fix ready before the end of the week. There are just a couple more tests we need to run through.

**Comment by ifrimere** [comment]
@vikdialpad - can you try out the 1.1.2 release here: https://github.com/AcclaroInc/craft-translations/releases/tag/1.1.2 and let us know if your issue is resolved. Thanks.

**Comment by vikdialpad** [comment]
@ifrimere awesome, I'll definitely try it out and follow up. Thanks!
