### ISSUE TITLE
Error deleting assets or entries

### ISSUE THREAD

**Issue by stephanwergles** [AcclaroInc/craft-translations#20]
Hi, 

i have installed translation plugin v1.1.1 and Craft 3.0.41. When I try to delete any asset or entry, it gives me an error notification of "An unknown error occurred." and the asset or entry remains. When I disable the translation plugin, deleting works again as usual. I tested on different environments, all same scenario. 

Does anybody have an idea what could be the issue here and how to fix that?

Thank you
Stephan

**Comment by sidedwards** [comment]
@stephanwergles v1.1.1 of the plugin actually requires Craft 3.1+ which supports soft-deletes. I would recommend upgrading Craft to 3.1+ or use [version 1.0.2 of the plugin](https://github.com/AcclaroInc/craft-translations/tree/1.0.2)

I'll go ahead and make ^3.1 a requirement in our composer settings for v1.1.1. Thanks!
