### ISSUE TITLE
Using getCanonicalId() instead of getSourceId() for drafts

### ISSUE THREAD

**Issue by sfsmfc** [AcclaroInc/craft-translations#202]
Removing deprecation messages for using getSourceId in Craft CMS until version 3.7.x by using getCanonicalId instead.

see also Pull-Request: https://github.com/AcclaroInc/craft-translations/pull/201

**Comment by ifrimere** [comment]
@sfsmfc - thank you for reporting this issue. We will have this issue addressed in v2.0 of the plugin due out by end of the month. I think the issue is actually already resolved in a WIP PR that is under QA right now. fyi @shnsumit @sidedwards

**Comment by sidedwards** [comment]
Closing; this was addressed in https://github.com/AcclaroInc/craft-translations/pull/184
