### ISSUE TITLE
Merge Issue with Drafts created From Plugin

### ISSUE THREAD

**Issue by masonry47** [AcclaroInc/craft-translations#211]
Hi!

We think we have uncovered a bug which seems to be related to the new Craft merge feature into drafts which recently added [matrix blocks](https://github.com/craftcms/cms/pull/7710).  This issue seems to only happen with Acclaro created drafts and we think it only occurs with drafts using Matrix blocks as a "page builder" type field.

Steps to recreate.

1. Create an entry using a matrix field and create a few different blocks (with different block types)
2. Create a translation order from that entry targeting multiple sites
3. At that point, the Acclaro drafts are created correctly.
4. Go back to "Current" entry in any language and make a content change to one of the matrix blocks.
5. Then return to an an Acclaro draft in a different language from where the change was made and you should see duplicates of each matrix block that was created.  Meaning, for example, lets assume I have 3 sites, english, french, and spanish.....if i updated the "current" french  entry, then the French Acclaro draft would be fine, but the Spanish draft would have the duplicate blocks.

I know this one is a little tough to describe, so happy to jump on a call anytime.

This is with Craft 3.7.13 and Acclaro v1.10.6

Thanks!

**Comment by sidedwards** [comment]
Hi there,

Thanks for reaching out; this is a known issue introduced in Craft 3.7.9, and we have addressed it in our upcoming v2.0 release.

PR for reference: https://github.com/AcclaroInc/craft-translations/pull/199

**Comment by ifrimere** [comment]
@masonry47 - we are planning to have v2.0 release ready within the next week or so. Thanks.

**Comment by masonry47** [comment]
Thanks @sidedwards and @ifrimere 

I think we found something else at least remotely related.  But when trying to apply translations that are translated matrix blocks, we are getting an "invalid owner id".  The translation does apply succesfully in one language but each other language gets the error.  See attachment and thanks!

![Screen Shot 2021-09-28 at 10 47 58 AM](https://user-images.githubusercontent.com/48130527/135123729-eac3e869-30e0-4e0b-a6ac-87f9a0587f02.png)

**Comment by sidedwards** [comment]
@masonry47 

This issue is resolved in [`release/2.0`](https://github.com/AcclaroInc/craft-translations/releases/tag/v2.0.0).
