### ISSUE TITLE
Order details template error

### ISSUE THREAD

**Issue by masonry47** [AcclaroInc/craft-translations#256]
Hi there, 

We recenlh updated to 2.0.3 are are getting a template vaiable error.  See screenshot and thanks!

<img width="1618" alt="Screen Shot 2021-11-08 at 4 35 54 PM" src="https://user-images.githubusercontent.com/48130527/140830069-20d85918-a137-45e9-a459-37930c3e339a.png">

**Comment by sidedwards** [comment]
@masonry47, thanks for reaching out; we'll investigate on our end and post an update here once we have more information.
