### ISSUE TITLE
Translations Plugin dashboard page gives SSL error

### ISSUE THREAD

**Issue by ryotadialpad** [AcclaroInc/craft-translations#26]
Repro step:
1. install Plugin
2. go to {admin}/translations

When I land on page, it displays following error:
GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /usr/share/nginx/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186

Even though site is certified with SSL
<img width="1461" alt="Screen Shot 2019-09-23 at 5 07 44 PM" src="https://user-images.githubusercontent.com/46463521/65471772-543dc000-de25-11e9-8b1d-5cba7a10092c.png">

Only get this error on Dashboard page and orders, translators, and about tabs loads without any issues.

Environment:
https://github.com/wyveo/nginx-php-fpm > Docker Tag: php71
Craft Version: 3.3.3
PGSQL: 9.6
Host: Google Cloud Platform, flex environment

**Comment by sidedwards** [comment]
https://github.com/AcclaroInc/craft-translations/commit/703e100c3a8fd4f9e9673b8cf61b57b661e22328 fixed this. Will include in the next patch release.
