### ISSUE TITLE
Merge and Apply Button

### ISSUE THREAD

**Issue by masonry47** [AcclaroInc/craft-translations#260]
Hey @sidedwards, we are seeing another issue with duplicating blocks, and some other strange behavior, in particular when using the merge and apply draft button, as opposed to using the "merge into draft" button, then applying with the entry.  When using the latter workflow, things seems to work fine (though there is some quirkiness here to). We think it may also have to do with this propagation setting

<img width="429" alt="Screen Shot 2021-11-11 at 11 47 42 AM" src="https://user-images.githubusercontent.com/48130527/141345060-4bc7dae1-69db-4d18-9b9f-02a119bc4d5f.png">

This one is a little difficult to write out or use screenshots, so hoping to do a screenshare with you. We are able to create the issue consistently and this is with 2.03.

Thanks!

**Comment by ifrimere** [comment]
@masonry47 - Please reference this ticket:  **Matrix blocks duplicate on save when creating a new entry** craftcms/cms#10130 (comment)

**Comment by sidedwards** [comment]
### 🆕 Updates
- FYI, @brandonkelly confirmed a fix in the next release https://github.com/craftcms/cms/issues/10130#issuecomment-984286189

### 🔗 References
> https://github.com/craftcms/cms/commit/6f2affcd15326f5dafb3155a6fc0c36224cba923 Fixed a bug where Matrix blocks within drafts could lose track of their canonical blocks when they were updated upstream, resulting in duplicated blocks. ([#10130](https://github.com/craftcms/cms/issues/10130))

**Comment by masonry47** [comment]
Thanks so much @sidedwards and @ifrimere!

**Comment by masonry47** [comment]
@sidedwards and @ifrimere,  we are continuing to see this issue after the update.  The scenario on the Craft issue is corrected with the Craft update, when we follow those steps all is good.  So I think (not positive) that this is on the plugin side and it still has to do with the " Let each entry choose ..." propagation setting.   When we "merge and apply" the behavior is still strange in that it adds the entry to ALL sites, rather than just the ones that the "order" was created for and we get duplicated matrix blocks for the first targeted site only.  All targeted sites after the first one do not duplicate matrix blocks. 

One thing to note is if we add the entry to all sites that we are targeting translations for BEFORE beginning the translation order process, everything works just fine.  

Thanks so much in advance for any thoughts on this!

**Comment by sidedwards** [comment]
@masonry47 please try with [`v2.1.1`](https://github.com/AcclaroInc/craft-translations/releases/tag/v2.1.1) to see if that resolves the issue for you.

**Comment by masonry47** [comment]
Thanks @sidedwards 

The update actually killed the backend with the following error.  Any ideas?  Thanks!

Class 'acclaro\translations\services\AcclaroService' not found

**Comment by masonry47** [comment]
@sidedwards just deleted previous comment....  reverted and reinstalled and all fine.  Will test on the issue and keep you posted.

**Comment by masonry47** [comment]
@sidedwards resolved.  Thanks!
