### ISSUE TITLE
Order not picking up translatable fields

### ISSUE THREAD

**Issue by ryotadialpad** [AcclaroInc/craft-translations#27]
Repro Steps: (assuming Multi site is already enabled and section has that multi site light switch turned on. and field's translation method is set to Translate for each Site)
1. Install Translation plugin
2. Create new section with multi site enabled
<img width="1101" alt="Screen Shot 2019-09-23 at 5 27 58 PM" src="https://user-images.githubusercontent.com/46463521/65472317-c911f980-de27-11e9-9e0c-420c3904b381.png">

3. Create new field with translation enabled
<img width="928" alt="Screen Shot 2019-09-23 at 5 27 18 PM" src="https://user-images.githubusercontent.com/46463521/65472335-d62ee880-de27-11e9-80a1-c09467d2669d.png">

4. Add that field to section
<img width="653" alt="Screen Shot 2019-09-23 at 5 28 36 PM" src="https://user-images.githubusercontent.com/46463521/65472346-e777f500-de27-11e9-85ff-66c32fc99255.png">

5. add Content to that field
<img width="1263" alt="Screen Shot 2019-09-23 at 5 29 01 PM" src="https://user-images.githubusercontent.com/46463521/65472361-f8286b00-de27-11e9-9b61-981da4ccc997.png">

6. after saving content, click on New Translation button from same content

Expected Behaviour:
Entry reference with word count to show translatable content.

Actual Behaviour (on our environment):
<img width="799" alt="Screen Shot 2019-09-23 at 5 29 14 PM" src="https://user-images.githubusercontent.com/46463521/65472412-37ef5280-de28-11e9-8370-0cf640890fb0.png">

No content is picked up as translatable content, unable to submit to create new order for translations

Environment:
https://github.com/wyveo/nginx-php-fpm > Docker Tag: php71
Craft Version: 3.3.3
PGSQL: 9.6
Host: Google Cloud Platform, flex environment

**Comment by sidedwards** [comment]
@ryotadialpad I've tested this with the environment information above and am unable to reproduce the issue.

Can you provide access to a staging environment so we can reproduce? Please send staging credentials to sid@reboundcreative.com

**Comment by ryotadialpad** [comment]
@sidedwards thanks for the reply, I'm setting environment for you at this moment. will send you credential soon as one is ready for you

**Comment by sidedwards** [comment]
Just updating this thread. Issue was caused by a 301 redirect issue on the host environment and was not related to the plugin.
