### ISSUE TITLE
Non-translatable title still included in translation order export

### ISSUE THREAD

**Issue by timrosskamp** [AcclaroInc/craft-translations#294]
When setting the entry title or asset title to be "not translatable" it's still included in the export when creating a translation order.

Is this by design? I expected this field to be excluded from the export since it will be overritten for other sites when importing again.

**Comment by sidedwards** [comment]
@timrosskamp, thanks for reporting; this issue was resolved in [`v2.1.2`](https://github.com/AcclaroInc/craft-translations/releases/tag/v2.1.2).

**Comment by timrosskamp** [comment]
Thanks for the quick fix!
