### ISSUE TITLE
.xml does not match any known entries.

### ISSUE THREAD

**Issue by bitboxth** [AcclaroInc/craft-translations#319]
When I export an XML file and import it translated, I always get the error:
'*.xml does not match any known entries.'
I simply created a new job, downloaded the XML file and uploaded it again.

The IDs of the matrix fields look different.

This is how it looks with a new export
```
<?xml version="1.0" encoding="utf-8"?>
<xml>
  <head>
    <original url="https://stage.kayserbetten.eu/"/>
    <preview url=""/>
    <sites source-site="1" target-site="4"/>
    <langs source-language="de-DE" target-language="es"/>
    <meta elementId="12325" orderId="85428" wordCount="348"/>
  </head>
  <body>
    <content resname="title">Homepage</content>
    <content resname="slug">homepage</content>
    <content resname="contextMatrix.73_44278.preHeadline">Über uns</content>
    <content resname="contextMatrix.73_44278.headline">Was wir machen</content>
....
```

This is the 'old' export with the current translations.
```
<?xml version="1.0" encoding="utf-8"?>
<xml>
  <head>
    <original url="https://stage.kayserbetten.eu/"/>
    <preview url=""/>
    <sites source-site="1" target-site="4"/>
    <langs source-language="de-DE" target-language="es"/>
    <meta elementId="12325" orderId="85428" wordCount="348"/>
  </head>
  <body>
    <content resname="title">Página web</content>
    <content resname="slug">pagina-web</content>
    <content resname="contextMatrix.84388.preHeadline">Acerca de nosotros</content>
    <content resname="contextMatrix.84388.headline">Experiencia e innovación</content>
....
```

Craft version: 3.7.23
PHP version: 7.4.28
PHP DOM Enabled: true
MultiSite: true
Plugin List: {"contact-form":"2.2.7","contact-form-extensions":"1.2.4","contact-form-honeypot":"1.0.2","cp-clearcache":"1.1.0","dumper":"2.0.0","matrixmate":"1.3.1","minifier":"2.0.5","picture":"2.2.2","redactor":"2.8.8","redirect":"1.1.1","translations":"v2.0.5","enupal-translate":"2.2.1"}

**Comment by ifrimere** [comment]
Issue resolved with newly created order export/import workflow.
