### ISSUE TITLE
Integrate with Smartling

### ISSUE THREAD

**Issue by tekstrand** [AcclaroInc/craft-translations#322]
We'd like to explore adding Smartling as a service into this plugin. Is that something that Acclaro would be open to receiving PRs into this repo for?

**Comment by blafferty** [comment]
Thank you for posting here, Tommy. Could you connect with me by email? blafferty@acclaro.com

**Comment by MerrittBoydston** [comment]
@blafferty was there any update from the client on this? If so, can we close this task?

**Comment by blafferty** [comment]
@MerrittBoydston They did not follow up with us. Okay to close
