### ISSUE TITLE
CraftCMS 4 Support

### ISSUE THREAD

**Issue by davidhellmann** [AcclaroInc/craft-translations#328]
Hey, are there plans to be ready with the CraftCMS 4 launch? Or maybe a rough timeline?

Thanks :)

**Comment by sidedwards** [comment]
@davidhellmann, we are still in the process of testing the plugin with Craft 4 (beta). We will update this ticket once we have more information regarding a timeline.

**Comment by davidhellmann** [comment]
Hey,

any news or rough timeline? Just asking you to plan how we go one with our craft4 update plan :)

Cheers

**Comment by sidedwards** [comment]
@davidhellmann, support for Craft 4 will be included with [`release/2.3.0`](https://github.com/AcclaroInc/craft-translations/tree/release/2.3.0) with an expected release for mid-June.

**Comment by davidhellmann** [comment]
Nice! Installed it.
When I go to settings > translations it comes up this:
```
TypeError
acclaro\translations\Translations::getSettingsResponse(): Return value must be of type mixed, none returned
```

**Comment by davidhellmann** [comment]
Hey @sidedwards, any news here? I do not want to be annoying but a rough new date would be great so that we can plan a little :) Thank you!

**Comment by shnsumit** [comment]
@davidhellmann  Hey,
We are planning to release `v3.0.0`  by the end of next week, the reported issue above should be handled on next release.

**Comment by lucascallado** [comment]
Thanks, @shnsumit and @sidedwards!
