### ISSUE TITLE
Microban EN translated pages are picking up EN URLs

### ISSUE THREAD

**Issue by lauriechu** [AcclaroInc/craft-translations#333]
**ISSUE:**
On this [newly created page](https://www.microban.com/tw/antimicrobial-solutions/overview/antimicrobial-additives)
- All the links in the (Craft) body/text field are going to EN pages
- (Buttons are okay but perhaps there was no need for translation)

**PROCESS:**

1. Content is created in EN as a New Entry in Craft
2. Links are added to the page by selecting "Link to an entry" (attached)
3. EN page is added to translation jobs
4. EN page is then translated (which includes EN link text)
5. EN URLs remain after translation
6. (Re)translated pages should take into consideration the existing URLs with language extension

**EXAMPLE:**

1. See [_Antimicrobials in Schools_](https://www.microban.com/antimicrobial-solutions/environments/education)
2. In EN, there are 4 links in the 3rd paragraph
3. If this were put through Acclaro translation, all 4 EN links would appear in translated pages
4. However, "high-traffic areas" page is not translated in other languages
5. So, in the [Spanish version](https://www.microban.com/es/antimicrobial-solutions/environments/education) (for example), "high-traffic areas" is not link text — only the 3 links **+** they go to /es pages, not EN

<img width="624" alt="Craft link to an entry" src="https://user-images.githubusercontent.com/23465026/169413200-e2d83aa8-0e1c-4dd1-ba7d-a2876d4ed0a4.png">

@sidedwards

**Comment by sidedwards** [comment]
@lauriechu, thanks for reaching out. From what you described, it seems that this particular issue is related to Redactor link settings. When reviewing the Redactor link settings in the referenced Entries, it looks like the link "sites" are set to English which would explain the issue you're seeing.

Would you mind updating the Site settings to "Multisite" to see if that resolves the issue?

### 📚 Resources
![CleanShot 2022-05-23 at 16 34 54@2x](https://user-images.githubusercontent.com/11489608/169916008-7b1fcc0e-d7ce-4cc7-adc9-b49f93878086.png)
