### ISSUE TITLE
Order Status Sync Issues

### ISSUE THREAD

**Issue by masonry47** [AcclaroInc/craft-translations#334]
Hey Acclaro!

We are having an issue with orders in Craft are showing as "In Progress" that are assigned as complete in Acclaro. 

Craft: 3.7.28
Acclaro Plugin:v2.1.4

Thanks!

**Comment by sidedwards** [comment]
@masonry47, thanks for reporting this issue. Could you please send any relevant logs to sid@semantic.dev?

**Comment by sidedwards** [comment]
Closing; this was an API issue and unrelated to the plugin.
