### ISSUE TITLE
Issue accessing order

### ISSUE THREAD

**Issue by ryan-kershner** [AcclaroInc/craft-translations#341]
Steps:

1. Synced and merged files in a different order with the same files for a different language (pt-br)
2. Attempted to access the order (ja)
3. Received error message
4. 
[error.txt](https://github.com/AcclaroInc/craft-translations/files/8872507/error.txt)
![image (10)](https://user-images.githubusercontent.com/75766620/172905223-8068f41d-cff2-4974-8077-088198b38be5.png)

**Comment by sidedwards** [comment]
@ryan-kershner this issue should be resolved as of [v2.2.2](https://github.com/AcclaroInc/craft-translations/releases/tag/v2.2.2).

**Comment by ryan-kershner** [comment]
Awesome, thanks!
