### ISSUE TITLE
3.0.1: Download fails with Firefox 

### ISSUE THREAD

**Issue by amkdev** [AcclaroInc/craft-translations#392]
I have heavy trouble downloading translations files (csv, xml) etc. with Firefox. 

No JS-Errors. Firefox seems to do something first but then no download request appears. 

By chance I have tried Chrome and it simply works.

**Comment by sidedwards** [comment]
@amkdev thank you for reporting this issue. We'll investigate this and see if we can reproduce.

**Comment by shnsumit** [comment]
@amkdev  Looks like this issue was in specific Firefox version. In the latest version `108.0.2` it is working fine. 

Feel free to add comment if you still see this issue in latest version.
