### ISSUE TITLE
craft commerce support?

### ISSUE THREAD

**Issue by jankohlbach** [AcclaroInc/craft-translations#394]
Hello,

just wanted to ask if there is a chance that we also can handle translations for product entries from craft commerce with your plugin. Haven't seen that anywhere.

**Comment by sidedwards** [comment]
Hi @jankohlbach, thank you for reaching out. We plan on including Craft Commerce support in v3.1 of the Translations plugin.

**Comment by jankohlbach** [comment]
hey @sidedwards 
thanks for the quick reply, sounds great that you want to add support ❤️

**Comment by sidedwards** [comment]
@jankohlbach fyi, we included support for Craft Commerce in [`v3.1.0`](https://github.com/AcclaroInc/craft-translations/releases/tag/v3.1.0). Let us know if you have any further questions.

**Comment by joshuakeck** [comment]
Hi @sidedwards, thanks for the craft commerce integration in the newest version!
We try to use it, but we cannot select any product or variant in the source entries selection of an new order.

![image](https://user-images.githubusercontent.com/5852634/205054681-528bebc7-46ee-4636-b804-2e154504a4f0.png)

We use the "Acclaro Craft Plugin" v3.1.0, Craft CMS 4.3.3. and Craft Commerce 4.2.2.

Is there something we need to configure?

**Comment by sidedwards** [comment]
Hi @jankohlbach; thank you for reaching out. We will add support for Commerce entry types within the entry selector. In the meantime, you can create orders for Commerce products by going to Products, selecting source entries, and clicking "New translation."

📚 Resources
![CleanShot 2022-12-05 at 12 12 56@2x](https://user-images.githubusercontent.com/11489608/205566842-d05ac600-1ed9-4680-9d55-e36f4485183b.png)
