### ISSUE TITLE
Error On Submitting Order

### ISSUE THREAD

**Issue by masonry47** [AcclaroInc/craft-translations#400]
Hey Acclaro team,

We are seeing a potential issue when submitting orders.  We are seeing this "Serialization of 'Closure' is not allowed" flash message in the CP.  But do not see anything related in the logs.  When testing locally we are sometimes able to successfully create an order with a single entry, but we always see the error when submitting an order with multiple entries.  

We are on Craft 4.2.2 and Translations 3.0.1

Thanks!

**Comment by sidedwards** [comment]
Hi @masonry47, thank you for reaching out. We haven't come across this error before; would you mind reaching out via email so we can follow up with the next steps to investigate further?

**Comment by sidedwards** [comment]
Resolved in https://github.com/AcclaroInc/craft-translations/pull/404
