### ISSUE TITLE
Feature: make slug field translation option-able on per order basis

### ISSUE THREAD

**Issue by bhupeshappfoster** [AcclaroInc/craft-translations#436]
Requesting new feature as some user facing issues when entry slug gets translated and they want a way to prevent this.

Created ticket from discussion https://github.com/AcclaroInc/craft-translations/discussions/434

Expected changes:
- A lightswitch (saying prevent slug translation for this order) inside advance section on order details page in order settings tab, which will be disabled by default and if the user enabled this the slug for entries in that order will not be sent for translations.

**Comment by shnsumit** [comment]
Changes done and released in [v3.2.6](https://github.com/AcclaroInc/craft-translations/pull/449)
