### ISSUE TITLE
Image Asset's title being included in XML when translations turned off

### ISSUE THREAD

**Issue by lelkins-beyondtrust** [AcclaroInc/craft-translations#439]
I’ve turned off translations on my asset’s title, but when I export the XML they are still included.  Is there a way to stop the title from being added to the XML file?

![image](https://github.com/AcclaroInc/craft-translations/assets/90857698/833b204c-dbed-4836-bc83-9fbfc328dd51)
![image](https://github.com/AcclaroInc/craft-translations/assets/90857698/828b4608-d431-4e1b-8dde-b0a28b0c26e5)

**Comment by MerrittBoydston** [comment]
@shnsumit was #release/3.2.6 able to resolve this issue?

**Comment by shnsumit** [comment]
@lelkins-beyondtrust  This case has been handled in the latest release [Release/3.2.6](https://github.com/AcclaroInc/craft-translations/pull/449) 
Please update to the latest version and check it, Closing this issue now, feel free to reach out in case still see the issue.

**Comment by lelkins-beyondtrust** [comment]
@shnsumit - I'm running Craft 3, but I see there was a 2.2.5 release yesterday that is supposed to resolve the issue.  We will try that, thanks!
