### ISSUE TITLE
Body text disappears when a new translation is applied

### ISSUE THREAD

**Issue by olga-kondra** [AcclaroInc/craft-translations#452]
Version of craft plugin:v3.2.3
Version of craft Craft:  CMS 4.3.6.1

Dear Acclaro team, 

I have tried to apply some translated pages which have been  returned from Acclaro. The order number is [#206422]

I was able to see  all of the the translated text in the preview. As soon as I had applied the text, only the translated headline appeared on the page. The body text had vanished. I tested it with several languages and the same issue appeared in all languages. This seems to be an old bug that hasn't been resolved. We were experiencing the same issue in the past. 

You can look at the applied translations in this translation folder. You will see that the text body is missing altogether. 
Unfortunately I am not able to upload screenshots over Github. I have sent some screenshots to Erin, who is our project manager. 

Kind regards, 
Olga

**Comment by olga-kondra** [comment]
@blafferty @bhupeshappfoster 
I believe that I have sufficiently described and documented the issue. 
I am happy to describe it again. When I apply a translations **all of the text** except for the headline is gone. There is simply no body text. 
I think we don't even need screenshots to describe this bug. The full translations is however still visible in the preview, before the translation is applied. @blafferty Could you kindly look into this issue yourself? Many thanks in advance for your help.

**Comment by eperry-acclaro** [comment]
Hi @bhupeshappfoster,
Olga shared this screenshot with me via email. Please review and let us know if it helps to clarify the issue.
![⚙-Intelligente-Automatisierung-eröffnet-Mitarbeitern-neue-Möglichkeiten-Blue-Prism (1)](https://github.com/AcclaroInc/craft-translations/assets/54545207/303f0e92-230c-4d80-b94c-1b1073d56125)

Thanks,
Erin

**Comment by olga-kondra** [comment]
@blafferty 

I suggested to reupload the exact same order once again to see if the error appears again. Please feel free to create an order on our stage site. Please name the order "Test oder" and add the date. Many thanks for your support.

**Comment by MerrittBoydston** [comment]
@blafferty do we have any updates from the client on this task?

Thank you
