### ISSUE TITLE
Twig error when update is available: "Impossible to access an attribute ("releases") on a boolean variable ("1")."

### ISSUE THREAD

**Issue by aelvan** [AcclaroInc/craft-translations#461]
![CleanShot 2023-09-04 at 11 51 31](https://github.com/AcclaroInc/craft-translations/assets/2675644/5c184331-8c3e-40fb-b2db-df1dd51a041b)

Resolved by updating to the latest version of the plugin.

PHP 8.2.9
Craft 4.4.17
Translations v3.2.9

**Comment by bhupeshappfoster** [comment]
@aelvan 

We tried to reproduce the issue but didn't see any, can you please provide us the steps following which we can see this error too?

**Dashboard page**
![image](https://github.com/AcclaroInc/craft-translations/assets/72725957/b6af2590-387c-4cc6-9945-33f7ab8b40b9)

**Utility updates**
![image](https://github.com/AcclaroInc/craft-translations/assets/72725957/fb302dc5-699a-408d-9f5d-6b38aabb9b31)

Note: Please let us know if you updated the craft version too when trying to fix this issue if yes do let us know which version were you at when you saw this error.

Version details:
- Craft: 4.5.3
- Php: 8.1
- Translations: 3.2.7

**Comment by aelvan** [comment]
When I first saw this, I was on Craft 4.4.17 and Translations 3.2.9. Upgraded to Craft 4.5.3 and Translations 3.2.10, and the error went away. 

Tried downgrading to 3.2.9 on Craft 4.5.3 now, and the same error appears.

Are you running that test in dev mode, if not Craft will not show the twig error, but it's still there.

**Comment by bhupeshappfoster** [comment]
@aelvan 

Thanks for bringing this issue in our notice.

**Update:**
This issue has been addressed in our next release which is expected to be released at end of this week or early next week.

**Comment by shnsumit** [comment]
Resolved in [Release/3.3.0](https://github.com/AcclaroInc/craft-translations/pull/472)
