### ISSUE TITLE
Make it possible to merge and apply drafts for disabled entries

### ISSUE THREAD

**Issue by aelvan** [AcclaroInc/craft-translations#463]
Not sure if this is a bug, or the intended behaviour. But if I try to merge and apply changes to an entry that's disabled (in the target language), nothing happens. I get a notification saying "Success: Translation draft(s) published", but the entry has not been translated.

**Comment by aelvan** [comment]
Just noticed that a new entry with the translated content was created in another section.. So that probably indicates a bug.

If I enable the entry in the target language, it works as expected.

**Comment by shnsumit** [comment]
@aelvan 
Thanks for bringing this issue to our notice, we appreciate your patience.

**Update:**
This issue has been addressed in our next release which is expected to be released by early next week.

**Comment by shnsumit** [comment]
Resolved in [Release/3.3.0](https://github.com/AcclaroInc/craft-translations/pull/472)
