### ISSUE TITLE
Google translation - 411 Length Required error

### ISSUE THREAD

**Issue by RubenColpaert** [AcclaroInc/craft-translations#466]
When using the google translator for large entities with a lot of data to translate we receive an error. In the logs we can find that the google API returns a "411 Length Required" error. 
This can be solved by sending the data as a JSON body, as the [official Google documentation](https://cloud.google.com/translate/docs/basic/translate-text-basic) states, rather than adding it as query parameters. 

From code I can see that the variables are given as [query paramaters](https://github.com/AcclaroInc/craft-translations/blob/master/src/services/api/GoogleApiClient.php#L119). 

I was also wondering why the [official php client](https://cloud.google.com/php/docs/reference/cloud-translate/latest) is not used to accomplish this.

**Comment by shnsumit** [comment]
@RubenColpaert 

Thank you for bringing up the issue, we greatly appreciate your feedback, and I wanted to provide you with an update on how we plan to address this concern.

In our next hotfix release, which we are planning for early next week, we will be implementing the official PHP client provided by Google for the Translator API. This client will ensure that data is transmitted in the appropriate format, effectively resolving the error and improving the overall reliability of our translation service.

If you have any further questions or concerns, please don't hesitate to reach out. 

Thank you for your understanding and collaboration.

**Comment by sidedwards** [comment]
@RubenColpaert, this issue should now be resolved as of https://github.com/AcclaroInc/craft-translations/releases/tag/v3.3.1

Please let us know if you experience further issues.
