### ISSUE TITLE
Page won't allow me to translate into targeted language

### ISSUE THREAD

**Issue by jacobaccesoo** [AcclaroInc/craft-translations#467]
I can't find the settings listed on the error message to fix this issue.

![Screenshot 2023-09-07 103747](https://github.com/AcclaroInc/craft-translations/assets/144463910/85ac5456-a1e2-48a5-83f9-0707853ae40a)

**Comment by shnsumit** [comment]
@jacobaccesoo  Looks like the target site is disabled that you want to translate.
Here are the steps that you need to follow to enable it:

Go to the **Settings -> Sections**

![image](https://github.com/AcclaroInc/craft-translations/assets/32937137/4b685eea-1412-47fe-82e8-2283b52e4560)

Click on the section for which you are translating the entry.

![image](https://github.com/AcclaroInc/craft-translations/assets/32937137/1db19113-92f5-4b38-9f31-92204b02bda2)

Enable the Site.

![image](https://github.com/AcclaroInc/craft-translations/assets/32937137/ff4a2c5d-6f4d-4dfb-b626-05214c1a89c0)

Let me know if you still need any help.
