### ISSUE TITLE
Compatibility with Craft 3.4.7.1?

### ISSUE THREAD

**Issue by gregkohn** [AcclaroInc/craft-translations#48]
I'm having trouble accessing any page -- admin or frontend -- since updating Craft to **3.4.7.1**.

Seeing the following error:

```
Class 'acclaro\translations\Order' not found
```

Removing the plugin eliminates the error. I tested this with plugin versions of **1.4.3** and **1.2.1**. Any chance there's something that needs to be patched on this end?

**Comment by ifrimere** [comment]
Hi Greg - we are actively working on version 1.5.0 of the plugin that will be compatible with Craft 3.4.x. Current and previous plugin versions are not compatible with 3.4.x so we are working hard to have plugin v1.5.0 ready before end of the month. If you have any 3.4 translation content needs that can’t wait until the end of the month let us know and we can see if a beta version of 1.5 could be made available to you. Thanks. - Ira (ifrimere@acclaro.com)

**Comment by blafferty** [comment]
Hi @gregkohn, Thank you for your post. Do you have a few minutes to discuss the plugin sometime this week? We'd like to learn a little more about your use case to better support you. Is Viget planning to localize? 
Kind regards, 
Bill (blafferty@acclaro.com)

**Comment by gregkohn** [comment]
@ifrimere Thanks for the quick response! That makes sense and that timeline is perfectly fine for us 👍 

@blafferty Sure, I can chat. It's actually one of our clients who is using the plugin to localize for their ecommerce site. This is still an in-progress effort, but I can do my best to answer any questions you have or pass them on to those who would know. Let me know. Greg (greg.kohn@viget.com)

**Comment by blafferty** [comment]
@gregkohn Thanks for letting me know. Will reach out by email with a few times to put on the calendar. Looking forward to speaking soon. -Bill

**Comment by ifrimere** [comment]
@gregkohn - version 1.5.0 of the plugin is now available: https://plugins.craftcms.com/translations. 

Please let us know any issues you run into installing it on Craft 3.4.x versions. Thank you.
