### ISSUE TITLE
Support for Hyper plugin?

### ISSUE THREAD

**Issue by johndwells** [AcclaroInc/craft-translations#497]
Hyper has, for many of us, become the defacto link field, surpassing LinkIt and Typed Link field: https://verbb.io/craft-plugins/hyper

And in fact, Hyper is the only one that is available for Craft 5. Both LinkIt and Typed Link field are no longer being developed.

Are there plans to support this plugin?

**Comment by MerrittBoydston** [comment]
Hi @johndwells, we're having internal conversations regarding supporting the Hyper plugin. We will update you here on our progress.

**Comment by MerrittBoydston** [comment]
Hello @johndwells, I wanted to update you on our progress. We are still assessing the support of Craft 5, once completed, we will begin work on supporting the Hyper plugin. I will continue providing the status of our progress on this ticket.
