### ISSUE TITLE
Craft 5 support?

### ISSUE THREAD

**Issue by johndwells** [AcclaroInc/craft-translations#498]
Are there plans to support Craft 5?

**Comment by MerrittBoydston** [comment]
Hi @johndwells, we're currently assessing the effort required to support Craft 5. We will notify you of any progress here.

Thank you

**Comment by turnstylerj** [comment]
Joining this thread. We have a client considering Acclaro for an upcoming build that will be on Craft 5.

**Comment by sidedwards** [comment]
@johndwells @turnstylerj we are currently reviewing Craft 5 support. We will update this thread once we have more information and an expected timeline.

**Comment by humandevs** [comment]
+1 !

**Comment by MerrittBoydston** [comment]
> We are also interested in Craft 5 Support. Are there any news regarding this topic?

Hello @BAM-Dennis we are in the process of providing Craft 5 support. I will update you in this ticket on our progress.

**Comment by samueljoos** [comment]
Hi,
We would like to use the plugin for a Craft 5 project we are starting at the moment. Could you provide a timeline for the expected stable release of the plugin?

**Comment by sidedwards** [comment]
Support for Craft 5 is now available!

https://plugins.craftcms.com/translations?craft5
