### ISSUE TITLE
Publishing an entry in one language unpublishes the corresponding entry in another language

### ISSUE THREAD

**Issue by blafferty** [AcclaroInc/craft-translations#501]
# This ticket was created in the wrong repo, it has been recreated [here](https://github.com/AcclaroInc/pm-craft-translations/issues/528) 
@MerrittBoydston @shnsumit @ainigo-metcalfe @nik-semantic 

## The bug
- Blue Prism localizes into 6 target langauges
- One person is responsible for approving and applying entries into four languages: ko, ja, es-mx, pt-br
- A second person is responsible for two: de and fr
- If person 1 applies an entry into the first four, and then at a later time, person 2 applies an entry into the remaining two, then the first batch of entries are reverted to 'Ready for review' state
- NB: This only impacts the target entries for the same source. 
- NB: Merging all entries into an order and applying them works fine. 

## Screen recording (4.19.24)
https://github.com/AcclaroInc/craft-translations/assets/54414273/5184ae0a-9d4c-4d6b-855c-56b3a58d79a1

## Screenshot
- In the screen recording, you see that I applied the 'ko' entry. Then I published 'ja'. 
- At the end, Olga shows that the 'ko' has reverted to the draft state. 'Ja' has reverted as well
<img src="https://github.com/AcclaroInc/craft-translations/assets/54414273/e747ec4c-0958-486d-9d91-46bef4dd261d" width="500">

## Order and login info

- Craft order: [March 22. 24 - 1](https://www.blueprism.com/ltsefs/translations/orders/detail/6263870)
- Corresponding My Acclaro order: [March 22. 24 - 1 (224969)](https://my.acclaro.com/orders/details/224969)

**Comment by sidedwards** [comment]
@bhupeshappfoster @shnsumit  we've had this issue a few times before. @shnsumit can you assist with this?

**Comment by shnsumit** [comment]
> @bhupeshappfoster @shnsumit we've had this issue a few times before. @shnsumit can you assist with this?

@sidedwards  Yes sure, will check this on Monday and share the updates.

**Comment by MerrittBoydston** [comment]
Same thing as 502 here @blafferty, we have recreated this ticket in the private repo https://github.com/AcclaroInc/pm-craft-translations/issues/527. Please let us know if we can close this one to remove excess noise.
