### ISSUE TITLE
Plugin stops static translations from working

### ISSUE THREAD

**Issue by khamer** [AcclaroInc/craft-translations#57]
It looks to me like the Acclaro Translation plugin blocks loading static message translations.

[These lines in TranslationRepository.php](https://github.com/AcclaroInc/craft-translations/blob/cffc251d9db70302291fac33817d6948360c1fff/src/services/repository/TranslationRepository.php#L143-L165) load Acclaro's translations into Craft/Yii's translation stuff, but because of [this line in Yii's MessageSource class](https://github.com/yiisoft/yii2/blob/master/framework/i18n/MessageSource.php#L106), once Acclaro's translations are loaded, the `$key` in `$this->_messages` exists, and it never calls `->loadMessages()`, etc.

You should be able to easily duplicate this by running the acclaro plugin with entries in translations_translations along with a [static translation file](https://docs.craftcms.com/v3/static-translations.html#prep-your-messages) for the same category/language.

Maybe there's a way to cause Craft to load all translations up front? It looks like to me that Craft only reads the translation files if it comes across a twig translate filter for that category/language.

I saw this on older versions, but it's definitely present on CraftCMS 3.4.5/Translations 1.5 as well as CraftCMS 3.4.14/Translations 1.5.1.

**Comment by sidedwards** [comment]
Hi @khamer nice catch, thanks for submitting this issue. We'll take a look at this and get a fix out as soon as we can.

Thanks!

**Comment by sidedwards** [comment]
@khamer Thanks for your patience with this, we included a fix in [v1.6.0](https://github.com/AcclaroInc/craft-translations/releases/tag/v1.6.0). We're now using a namespaced category for static translations so we don't interfere with static site translations.

To use the plugin's static translations (for displaying translated dropdowns/multiselect field values) you can use `{{ 'some string'|t('translations') }}` in your theme templates.
