### ISSUE TITLE
Unable to modify and browse "Messages"

### ISSUE THREAD

**Issue by joelstrom** [AcclaroInc/craft-translations#59]
Hello

I am unable to browse the messages section through the pagination. Every time I press one of the arrows or page numbers it reloads the same page view again. There is some Javascript error that happens each time (Cannot read property 'split' of undefined).

Search doesn't seem to do anything either, but I am guessing that it's related to the same problem.

Craft CMS 3.4.17.1
Translations 2.0.3

Any help would be greatly appreciated! Thank you!

**Comment by blafferty** [comment]
Hi @joelstrom , Thanks for your note. We're taking a look at this, will circle back.

Kind regards,
Bill

**Comment by blafferty** [comment]
Hi @joelstrom , 

Could you share a few screenshots to help us better understand the issue? I'd be happy to jump on a call with you and do a screenshare to start troubleshooting. 

Thanks.
Bill

**Comment by joelstrom** [comment]
Hello @blafferty 

I am sorry, I confused this plugin for another one completely (MutationDigitale/craft3-translate).
You can close/delete this issue!

- Joel
