### ISSUE TITLE
Non breaking spaces cause error on import

### ISSUE THREAD

**Issue by matthewmrotter** [AcclaroInc/craft-translations#70]
When importing an XML file, if there's an nbsp; in the document it causes an error on import. 

Deleting the space and re-uploading fixes the issue

**Comment by ifrimere** [comment]
@matthewmrotter - thank you for reporting this. What the space in the filename or in the actual file somewhere? I just tried importing a zip file with a space in the file name and wasn't able to repro the error. Any additional details you can provide are appreciated.  Thanks.

fyi @sidedwards

**Comment by matthewmrotter** [comment]
Here's the exact line 

`    <content resname="faqs.1328983.question.1328985.question">Qu'est-ce que la RPA connectée&nbsp;?</content>`

It also throws an error when trying to open the XML file inside of a browser.

**Comment by ifrimere** [comment]
@matthewmrotter - thanks for the update.  Given this is technically 'invalid XML', I don't see this as a bug with the Translations plugin. Do you agree?

![image](https://user-images.githubusercontent.com/20604655/86935289-a7f66d00-c10a-11ea-8462-8abba786629b.png)

**Comment by matthewmrotter** [comment]
Good point! 

We sent it over and then tried to import via import/export and it threw us a bug. So it was a translator on the Acclaro side that added in a non-breaking space. 

The member of our team who tried to import isn't familiar with reading XML documents so was confused why it was wasn't importing. 

Not sure if the fix is making sure translators don't use that type of spacing, removing these characters when we download the file, or purifying it on upload. Just something I though y'all should be aware of.

**Comment by ifrimere** [comment]
@matthewmrotter - agreed, this is a bug with the translation file delivery. I will report it to our localization engineering department who can possibly script a warning in our CAT tool to avoid this condition from happening again. Thank you for bringing this to our attention.
