### ISSUE TITLE
Is the plugin compatible with `project.yaml` and multiple environments?

### ISSUE THREAD

**Issue by taylordaughtry** [AcclaroInc/craft-translations#71]
Hi!

I'm encountering an issue where the plugin doesn't seem to install "properly" when using multiple environments, some with disabled admin changes. Specifically, I'm seeing this error when attempting to sync `project-config` in another environment:
`Changes to the project config are not possible while in read-only mode.`

I'd imagine that since admin changes are disabled, and installing this plugin runs migrations that don't go through the projectConfig service, the error makes sense, and the plugin isn't compatible with this situation—but if I'm missing something, just let me know! (I'd love to be wrong and just correct something errant I'm doing on my end!)

Here's some context:
- Craft 3.4.23
- acclaro/translation @ 1.7.0
- Two environments: local + staging
- Host: Heroku (using Pipelines)

**Comment by sidedwards** [comment]
Hi @taylordaughtry thanks for bringing this to our attention, we'll investigate including [projectConfig support](https://docs.craftcms.com/v3/extend/project-config.html#implementing-project-config-support) in an upcoming release.

**Comment by taylordaughtry** [comment]
@sidedwards  Thanks; I appreciate the fast response! Do you have a rough idea of timeline? (Days, weeks, or months?)

**Comment by sidedwards** [comment]
@taylordaughtry just curious, have you tried running `composer install` [prior to attempting the sync](https://docs.craftcms.com/v3/project-config.html#caveats)?

**Comment by taylordaughtry** [comment]
@sidedwards I have! It's a part of the deployment workflow. (And it occurs before the sync, to be sure everything's in place for it)

**Comment by taylordaughtry** [comment]
Thinking through the process, I wonder if it's not the `migrate/all` that's causing the issue?

**Comment by sidedwards** [comment]
@taylordaughtry thanks for bringing this issue to our attention. This issue should be resolved in [v1.7.1](https://github.com/AcclaroInc/craft-translations/releases/tag/v1.7.1)

**Comment by taylordaughtry** [comment]
@sidedwards  I think we're seeing this issue again, and it'll actually require the project config to be checked—the newest migration (adding the categorydrafts table) is causing the same error when running on staging.

The docs for Craft note this exact situation here; it's worth checking out (under "Consider this scenario"):
https://craftcms.com/docs/3.x/extend/project-config.html#project-config-migrations

**Comment by sidedwards** [comment]
Hi @taylordaughtry would you mind testing the following code for `m200617_105526_create_category_draft_table.php`

``` php
public function safeUp()
{
    $schemaVersion = Craft::$app->projectConfig
    ->get('plugins.translations.schemaVersion', true);

    if (version_compare($schemaVersion, '1.3.1', '<')) {
        echo "Creating translations_categorydrafts table...\n";
        $this->dropTableIfExists('{{%translations_categorydrafts}}');

        $this->createTable(
            '{{%translations_categorydrafts}}',
            [
                'id'            => $this->primaryKey(),
                'name'          => $this->string()->notNull(),
                'title'         => $this->string()->notNull(),
                'categoryId'    => $this->integer()->notNull(),
                'site'          => $this->integer()->notNull(),
                'data'          => $this->mediumText()->notNull(),
                'dateCreated'   => $this->dateTime()->notNull(),
                'dateUpdated'   => $this->dateTime()->notNull(),
                'uid'           => $this->uid()
            ]
        );

        echo "Done creating translations_categorydrafts column...\n";
    }
}
```

**Comment by taylordaughtry** [comment]
Sure; testing that now!

**Comment by sidedwards** [comment]
@taylordaughtry did the updated migration above resolve the issue you were experiencing?

**Comment by taylordaughtry** [comment]
@sidedwards  Hi! Follow up here—the issue was on our side; Heroku was deploying in such a way that the `project.yaml` changes weren't on the server when migrations were run. All good!
