### ISSUE TITLE
Add support for Volumes to address an import error when using separate web/worker instances.

### ISSUE THREAD

**Issue by taylordaughtry** [AcclaroInc/craft-translations#77]
Hey!

For projects where the instance processing the job and the instance serving the CP are different, the plugin's `Updating translation drafts` job currently throws an error due to a missing file. (Since the upload is in the `tempuploads` directory of the worker instance, it wouldn't be in the `tempuploads` directory of the CP instance.)

```
DirectoryIterator::__construct(/app/storage/runtime/assets/tempuploads/88723): failed to open dir: No such file or directory
```

It'd be awesome if we could tell the plugin to use a Volume (like S3) to account for these types of situations! Would that be possible? (@sidedwards)

**Comment by ifrimere** [comment]
@taylordaughtry - supporting a multi-server Craft configuration is on our roadmap but we don't have a firm ETA for its support  just yet. We'll investigate some more next week and let you know.  (fyi @sidedwards)

**Comment by sidedwards** [comment]
@taylordaughtry have you looked into setting up a NFS for your storage directory?

- https://craftcms.stackexchange.com/questions/4719/load-balancing-nodes-configuration-3-craft-nodes-behind-f5-big-ip/4729#4729
- https://craftcms.stackexchange.com/questions/18687/do-servers-in-a-multi-server-craft-setup-need-to-share-a-storage-directory

**Comment by taylordaughtry** [comment]
@sidedwards Unfortunately, because of Heroku's architecture we can't mount NFS and share it between the two instances.

**Comment by taylordaughtry** [comment]
Update on the above—looks like it's not possible. Since we can't mount a shared filesystem between the two instances, we're out of options, short of forking it on our side and updating the plugin!

**Comment by taylordaughtry** [comment]
At a high-level, the patch would essentially be updating the code around this line to use a Volume (which could be specified as a plugin setting), then saving the file to that Volume and passing the Asset ID to the Job.

**Comment by ifrimere** [comment]
@taylordaughtry - we are investigating this feature for support in an upcoming sprint later this month or latest, early next month

**Comment by sidedwards** [comment]
Volumes support was added in [v1.7.2](https://github.com/AcclaroInc/craft-translations/releases/tag/v1.7.2) courtesy of @taylordaughtry.

PR https://github.com/AcclaroInc/craft-translations/pull/82
