### ISSUE TITLE
Translating Asset Fields

### ISSUE THREAD

**Issue by linchpinstudios** [AcclaroInc/craft-translations#8]
We have an 'alt' field on our assets that needs to be translated, how do we add the fields on assets that need to be translated to an order?

**Comment by sidedwards** [comment]
@linchpinstudios We don't currently have support for asset alt fields but have plans to add it in the near-term future.

**Comment by sidedwards** [comment]
Support for translating Asset fields was added in [v1.8.0](https://github.com/AcclaroInc/craft-translations/releases/tag/v1.8.0)
