### ISSUE TITLE
Should the Target Site of an Order have a foreign key to the Site, so it's deleted when the target Site is deleted?

### ISSUE THREAD

**Issue by taylordaughtry** [AcclaroInc/craft-translations#86]
While I was testing locally, I encountered a minor issue where the Orders index screen threw an error—

`SiteRepository@getSiteLanguageDisplayName()@179: getLocaleById() requires string, null given`: https://github.com/AcclaroInc/craft-translations/blob/b66d6ccd82812cbef8f1528227d53e2f525b07f1/src/services/repository/SiteRepository.php#L175-L182

The issue stemmed from a few orders I made for a Site that was later deleted—since that site no longer exists, `getSiteLanguage()` was returning `null` and passing that value to the `getLocaleById()` method.

Super quick-fix, and not a blocker at all! But, I did want to ask this question to see if there was something happening elsewhere that prevented a foreign key being added to prevent this in the future!

**Comment by ifrimere** [comment]
@taylordaughtry - thanks for posting this. We will look into a fix in an upcoming sprint. If it's something that does start to become more of an issue for you and your client, please let us know and we can try to escalate a fix, or if you decide to fix on your own, please do submit another PR. Thanks.

**Comment by taylordaughtry** [comment]
Hey! Sure; will do. Definitely not a blocker at all, moreso just a thing I wanted to note for future reference. Thanks!

**Comment by sidedwards** [comment]
@taylordaughtry thanks again for reporting this. When a Site is deleted, Craft generally doesn't remove the record, but instead [soft deletes](https://craftcms.com/docs/3.x/extend/soft-deletes.html) it, so a foreign key might not be our best option. That said, `v1.9.0` includes better support for Sites that are deleted.
