### ISSUE TITLE
Use Craft's native XML export feature when generating XML for orders.

### ISSUE THREAD

**Issue by taylordaughtry** [AcclaroInc/craft-translations#88]
This is 100% a feature request, to be clear:

It'd be fantastic if we were able to export content with the (now) native XML exports. It'd let the plugin 'lean' on Craft's developers to provide support for various fields, taking a significant load off support needs. 

The biggest barrier is the significant difference in XML structure between Craft's exports and this plugin's—that's likely where most of the work would lie.

Just a feature request, of course! This would be a _huge_ win for workflow, being able to export content from any site to provide what's needed for translation.

**Comment by ifrimere** [comment]
@taylordaughtry - thanks for sharing this idea! We'll do some investigation of the strengths and any weaknesses related to Craft's native export XML functionality vs. how the Translation plugin currently builds out its export files (which the import files need to keep the header structure of, so when time for importing translations, all the translated content can properly go where it's supposed to).

**Comment by semantic-support** [comment]
Thank you @taylordaughtry and @ifrimere for bringing this to our attention. We'll do some investigation on this feature request and be sure to notify you on its progress.

**Comment by ifrimere** [comment]
@taylordaughtry - thanks for this suggestion. @sidedwards and our dev team put quite a bit of research into this, but the lack of features the native Craft XML export provides that are needed to match up all the fields on translations import for right now, make the effort to switch over our current app;s infrastructure not worth doing. We will however keep an eye on how Craft further evolves their native XML export functionality though and if things change will consider the refactor.
